version: '3.8'

services:
  policeman-ssh:
    build:
      context: .
      dockerfile: Dockerfile.ssh
    container_name: claude-policeman-ssh
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - AGENT_ROLE=policeman
      - AUTO_UPDATE_CLAUDE=${AUTO_UPDATE_CLAUDE:-false}
    volumes:
      - ./projects:/workspace/projects
      - ./hooks:/workspace/hooks:ro
      - ./.env:/workspace/.env:ro
      - policeman-claude:/home/developer/.claude
      - policeman-cache:/home/developer/.cache
    ports:
      - "2222:22"  # SSH on port 2222
      - "8081:8080"  # Web UI on different port
    networks:
      - claude-net
    restart: unless-stopped

networks:
  claude-net:
    external: true
    name: claude-swarm-docker-spawn_claude-net

volumes:
  policeman-claude:
    external: true
    name: claude-swarm-docker-spawn_policeman-claude
  policeman-cache:
    external: true
    name: claude-swarm-docker-spawn_policeman-cache